# ATS 2.0 Monitoring Configuration
# WebSocket daemon and web interface settings

# Database configuration
db:
  host: 10.8.0.1
  port: 5432
  database: fox_crypto
  user: elcrypto
  password: LohNeMamont@!21

# Binance configuration
binance:
  enabled: true
  api_key: d1ee99de604c94e5bad271632534722abb39bb3d8746043184a270a29101d5b8
  api_secret: 559bb311c1eeae3c5d9bddd97e5b51f4a0349eed30f537d1965d0340b2d44995
  testnet: true

# Bybit configuration
bybit:
  enabled: true
  api_key: WrG37DUFHbejVGkqU2
  api_secret: ACUTQBTtKGfGKtH0D19IS9xYUCwiRuofLJf6
  testnet: true

# Monitoring settings
monitoring:
  position_update_interval: 1  # seconds
  balance_update_interval: 30  # seconds
  cleanup_interval: 3600  # seconds (1 hour)
  health_check_interval: 30  # seconds
  keep_closed_positions_days: 7  # days

# Web interface settings
web:
  host: 0.0.0.0
  port: 8000
  workers: 4
  reload: false
  cors_origins:
    - "*"

# Logging
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/monitoring.log
  max_size: 10485760  # 10MB
  backup_count: 5

# Alert settings (optional)
alerts:
  enabled: false
  telegram:
    bot_token: ${TELEGRAM_BOT_TOKEN}
    chat_id: ${TELEGRAM_CHAT_ID}
  thresholds:
    max_positions: 100
    max_drawdown_percent: 10
    min_balance_usd: 100